# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868480b8e5037c81f6f83b1c66108a0c769e2f61280dc2a19b789b65fc09c03159bf36df3924bbc774f5d2ed2534d874736078199d343df818592cfd4a923b5d

test:
  secret_key_base: 53a7290a26e519621146a41635b4ba5dd5663249d85e2de794c0781efa476faca31a758ecd00f801bd045554204f632a558ea367c5624a5837332d1bcbcd7e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
